name: cine-explorer
options:
  bundleIdPrefix: com.example
  deploymentTarget:
    iOS: '15.0'
  createIntermediateGroups: true
settings:
  base:
    SWIFT_VERSION: '5.5'  # Ajuste para a sua versão do Swift

targets:
  cine-explorer:
    type: application
    platform: iOS
    sources: Sources/cine-explorer
    resources: Sources/cine-explorer/Resources
    settings:
      base:
        ENABLE_USER_SCRIPT_SANDBOXING: NO
        ASSETCATALOG_COMPILER_APPICON_NAME: AppIcon
        INFOPLIST_FILE: Sources/cine-explorer/Info.plist
        UILaunchStoryboardName: LaunchScreen

  cine-explorer-tests:
    type: bundle.unit-test
    platform: iOS
    sources: Sources/cine-explorer-tests
    settings:
      base:
        INFOPLIST_FILE: Sources/cine-explorer-tests/Info.plist
    dependencies:
      - target: cine-explorer

schemes:
  cine-explorer:
    build:
      targets:
        cine-explorer: all
  cine-explorer-tests:
    build:
      targets:
        cine-explorer-tests: all